# The Docker image that will be used to build your app
image: node:lts

stages:
  - build

build_pomodoro:
  stage: build
  script:
    - cd pomodoro_app
    - npm install
    - npm run build
    - mkdir -p ../public/pomodoro_app
    - mv dist/* ../public/pomodoro_app
  artifacts:
    paths:
      - public
  only:
    - main
