image: node:latest

stages:
  - build
  - deploy

build_pomodoro:
  stage: build
  script:
    - cd pomodoro_app
    - npm install
    - npm run build
    - ls -al dist/assets
  artifacts:
    paths:
      - pomodoro_app/dist/ # Change this path to the correct location
  only:
    - main


# build_another_app:
#   stage: build
#   script:
#     - cd another-app
#     - npm install
#     - npm run build
#   artifacts:
#     paths:
#       - another-app/dist/
#   only:
#     - main


pages:
  stage: deploy
  script:
    - mkdir -p public/pomodoro_app
    - mv pomodoro_app/dist/* public/pomodoro_app # Ensure the source path here is correct
    - ls -al public/pomodoro_app
    - ls -al public/pomodoro_app/assets
  # - mkdir -p public/another-app
  # - mv another-app/dist/* public/another-app
  artifacts:
    paths:
      - public
  only:
    - main
