image: node:latest

stages:
  - build

build_pomodoro:
  stage: build
  script:
    - cd pomodoro_app
    - npm install
    - npm run build
    - mkdir -p ../public/pomodoro_app
    - mv dist/* ../public/pomodoro_app
  artifacts:
    paths:
      - public
  only:
    - main

# build_another_app:
#   stage: build
#   script:
#     - cd another-app
#     - npm install
#     - npm run build
#     - mkdir -p ../public/another-app
#     - mv dist/* ../public/another-app
#   artifacts:
#     paths:
#       - public
#   only:
#     - main
#
